#!/usr/bin/env node
// Generic script: read a normalized JSON array of POIs and produce an SQL file
// that upserts into `places` using (source, source_id) uniqueness.
// Usage: node scripts/upsert_places_from_normalized.js --input=path/to/normalized.json --out=path/to/out.sql

const fs = require('fs');
const path = require('path');

function parseArgs() {
  const args = {};
  for (const a of process.argv.slice(2)) {
    const m = a.match(/^--([a-zA-Z0-9_-]+)=(.*)$/);
    if (m) args[m[1]] = m[2];
  }
  return args;
}

function extractLonLat(item) {
  if (!item) return null;
  if (item.lng != null && item.lat != null) return { lon: Number(item.lng), lat: Number(item.lat) };
  if (item.lon != null && item.lat != null) return { lon: Number(item.lon), lat: Number(item.lat) };
  if (item.geometry && Array.isArray(item.geometry.coordinates)) {
    const [lon, lat] = item.geometry.coordinates;
    return { lon: Number(lon), lat: Number(lat) };
  }
  if (item.location && item.location.lng != null && item.location.lat != null) {
    return { lon: Number(item.location.lng), lat: Number(item.location.lat) };
  }
  return null;
}

function quoteSql(str) {
  if (str === null || str === undefined) return 'NULL';
  return "'" + String(str).replace(/'/g, "''") + "'";
}

function jsonbSql(obj) {
  if (obj === null || obj === undefined) return 'NULL';
  return quoteSql(JSON.stringify(obj));
}

async function main() {
  const args = parseArgs();
  const input = args.input || args.i;
  const out = args.out || args.o || 'scripts/data/upsert_places.sql';
  if (!input) {
    console.error('Missing --input path');
    process.exit(2);
  }

  const absInput = path.resolve(process.cwd(), input);
  const absOut = path.resolve(process.cwd(), out);

  const raw = fs.readFileSync(absInput, 'utf-8');
  let arr = [];
  try {
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed)) arr = parsed;
    else if (parsed && Array.isArray(parsed.features)) {
      // GeoJSON FeatureCollection
      arr = parsed.features.map(f => ({ ...f.properties, geometry: f.geometry }));
    } else if (parsed && typeof parsed === 'object') {
      // Accept objects with arrays under keys like buildings, facilities, pois, nodes
      const candidates = ['places', 'pois', 'data', 'features', 'nodes', 'facilities', 'buildings'];
      for (const k of Object.keys(parsed)) {
        if (Array.isArray(parsed[k])) {
          const items = parsed[k].map(it => {
            // For GeoJSON-like building entries, attach geometry if present
            if (it.geometry) return { ...it.properties, geometry: it.geometry };
            return it;
          });
          arr = arr.concat(items);
        }
      }
      // If we still have nothing, try known top-level candidate keys
      if (arr.length === 0) {
        for (const k of candidates) {
          if (Array.isArray(parsed[k])) arr = arr.concat(parsed[k]);
        }
      }
      if (arr.length === 0) throw new Error('Unrecognized JSON shape: no array-valued keys found');
    } else throw new Error('Unrecognized JSON shape: expected array or object with arrays');
  } catch (err) {
    console.error('Failed to parse input JSON:', err.message);
    process.exit(2);
  }

  const lines = [];
  lines.push('-- Generated by scripts/upsert_places_from_normalized.js');
  lines.push('BEGIN;');

  for (const item of arr) {
    const source = item.source || item.provider || item._source || 'osm';
    const source_id = item.source_id || item.id || item.osm_id || item.osm || null;
    const name = item.name || (item.tags && item.tags.name) || null;
    const category = item.category || item.type || (item.tags && item.tags.amenity) || null;
    const subtype = item.subtype || item.sub_type || null;
    const description = item.description || item.desc || null;
    const tags = item.tags || item.raw_tags || item.properties || null;
    const images = item.images || item.photos || null;
    const rating = item.rating || item.score || null;
    const rawObj = item.raw || item;
    const osm_id = item.osm_id || item.osmId || null;

    let loc = extractLonLat(item);
    if (!loc && item.centroid && Array.isArray(item.centroid.coordinates)) {
      const [lon, lat] = item.centroid.coordinates;
      loc = { lon: Number(lon), lat: Number(lat) };
    }
    const geomSql = loc ? `ST_SetSRID(ST_MakePoint(${loc.lon}, ${loc.lat}), 4326)::geography` : 'NULL';

    const cols = [
      'osm_id',
      'source',
      'source_id',
      'name',
      'category',
      'subtype',
      'description',
      'tags',
      'images',
      'rating',
      'raw',
      'geom'
    ];

    const vals = [
      osm_id === null ? 'NULL' : Number(osm_id),
      quoteSql(source),
      source_id === null ? 'NULL' : quoteSql(String(source_id)),
      quoteSql(name),
      quoteSql(category),
      quoteSql(subtype),
      quoteSql(description),
      jsonbSql(tags),
      jsonbSql(images),
      rating == null ? 'NULL' : Number(rating),
      jsonbSql(rawObj),
      geomSql
    ];

    const insert = `INSERT INTO places (${cols.join(',')}) VALUES (${vals.join(',')})` +
      ` ON CONFLICT (source, source_id) DO UPDATE SET
        osm_id = EXCLUDED.osm_id,
        name = EXCLUDED.name,
        category = EXCLUDED.category,
        subtype = EXCLUDED.subtype,
        description = EXCLUDED.description,
        tags = EXCLUDED.tags,
        images = EXCLUDED.images,
        rating = EXCLUDED.rating,
        raw = EXCLUDED.raw,
        geom = COALESCE(EXCLUDED.geom, places.geom),
        created_at = COALESCE(places.created_at, now())` +
      ' ;';

    lines.push(insert);
  }

  lines.push('COMMIT;');
  fs.mkdirSync(path.dirname(absOut), { recursive: true });
  fs.writeFileSync(absOut, lines.join('\n') + '\n', 'utf-8');
  console.log('Wrote', absOut, 'with', arr.length, 'rows');
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
